-- 코드를 입력하세요
WITH TH_FEE AS (SELECT C.CAR_ID, C.CAR_TYPE, 30*C.DAILY_FEE*(1 - (P.DISCOUNT_RATE*0.01)) AS FEE
        FROM CAR_RENTAL_COMPANY_CAR C RIGHT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
        ON C.CAR_TYPE=P.CAR_TYPE
        WHERE P.DURATION_TYPE='30일 이상'AND C.CAR_TYPE IN ('세단','SUV'))

SELECT F.CAR_ID, F.CAR_TYPE, F.FEE
FROM TH_FEE F, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE F.CAR_ID=H.CAR_ID
AND (H.CAR_ID, H.END_DATE) IN (SELECT CAR_ID, MAX(END_DATE)
                                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                                GROUP BY CAR_ID)
AND TO_CHAR(H.END_DATE,'YYYY-MM-DD')<'2022-11-01'
AND F.FEE >=500000 AND F.FEE < 2000000
ORDER BY F.FEE DESC, F.CAR_TYPE, F.CAR_ID DESC;