-- 코드를 입력하세요
SELECT to_char(B.SALES_DATE,'YYYY') AS YEAR
,TO_NUMBER(to_char(B.SALES_DATE,'MM')) AS MONTH
,COUNT(DISTINCT(A.USER_ID)) AS PUCHASED_USERS
,ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = 2021), 1) PUCHASED_RATIO
FROM USER_INFO A
JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE A.JOINED BETWEEN to_date('20210101','YYYYMMDD') AND to_date('20211231','YYYYMMDD')
GROUP BY to_char(B.SALES_DATE,'YYYY'),to_char(B.SALES_DATE,'MM')
ORDER BY 1,2