-- 코드를 입력하세요
SELECT 
 A.USER_ID AS USER_ID, A.NICKNAME AS NICKNAME, C.PRICE AS TOTAL_SALES
FROM USED_GOODS_USER A
JOIN (SELECT B.WRITER_ID AS WRITER_ID,SUM(PRICE) AS PRICE
        FROM USED_GOODS_BOARD B
      WHERE STATUS = 'DONE'
      GROUP BY WRITER_ID
) C
ON A.USER_ID = C.WRITER_ID
WHERE C.PRICE >= 700000
ORDER BY TOTAL_SALES;