-- 코드를 입력하세요
-- SELECT A.PRODUCT_ID,A.PRODUCT_NAME,   AS TOTAL_SALES
-- FROM FOOD_PRODUCT A
-- JOIN FOOD_ORDER B
-- ON A.PRODUCT_ID = B.PRODUCT_ID
-- GROUP BY A.PRODUCT_ID,A.PRODUCT_NAME
-- HAVING EXTRACT(B.PRODUCE_DATE FROM YEAR) = '2022'
-- AND EXTRACT(B.PRODUCE_DATE FROM MONTH) = '05'
-- ORDER BY TOTAL_SALES DESC , A.PRODUCT_ID
SELECT A.PRODUCT_ID,A.PRODUCT_NAME, A.PRICE * B.AMOUNT  AS TOTAL_SALES
FROM 
FOOD_PRODUCT A
JOIN 
( SELECT PRODUCT_ID , SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER 
WHERE EXTRACT(YEAR FROM PRODUCE_DATE) = '2022'
AND EXTRACT(MONTH FROM PRODUCE_DATE) = '05'
GROUP BY PRODUCT_ID ) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC , A.PRODUCT_ID
