-- 코드를 작성해주세요

SELECT B.ITEM_ID, B.ITEM_NAME, B.RARITY
FROM
    (SELECT ITEM_ID
    FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID
             FROM ITEM_INFO 
             WHERE RARITY = 'RARE')
     ) A
     JOIN ITEM_INFO B
     ON A.ITEM_ID = B.ITEM_ID
ORDER BY B.ITEM_ID DESC