-- 코드를 입력하세요
-- SELECT COUNT(*) AS USERS
-- FROM USER_INFO
-- WHERE AGE BETWEEN 20 AND 29
-- AND to_char(JOINED,'YYYY') = '2021'


SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE AGE BETWEEN 20 AND 29
AND JOINED BETWEEN to_date('20210101','YYYYMMDD') AND to_date('20211231','YYYYMMDD')